In [1]:
import pandas as pd
import numpy as num_paths
import matplotlib.pyplot as psnrResault
import seaborn as sns
sns.set(style="whitegrid")
import warnings
warnings.filterwarnings("ignore")
from matplotlib import pyplot as plt

/home/gurhancoban/.local/lib/python3.10/site-packages/pandas/core/arrays/masked.py:62: UserWarning: Pandas requires version '1.3.4' or newer of 'bottleneck' (version '1.3.2' currently installed).
  from pandas.core import (
/usr/lib/python3/dist-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.17.3 and <1.25.0 is required for this version of SciPy (detected version 1.26.2
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

In [2]:
df1=pd.read_csv("data21.11.2024-topo1.csv")
df2=pd.read_csv("data21.11.2024-topo2.csv")
df3=pd.read_csv("data21.11.2024.csv")

In [3]:
df1=pd.DataFrame(df1)
df2=pd.DataFrame(df2)
df3=pd.DataFrame(df3)

In [7]:
df1["kayitboyut"]=df1["kayitboyut"]-161196
df1["kayip"]=df1["kaynak"]-df1["kayitboyut"]
df1["kayip_orani"]=df1["kayip"]/df1["kaynak"]*100

df2["kayitboyut"]=df2["kayitboyut"]-161196
df2["kayip"]=df2["kaynak"]-df2["kayitboyut"]
df2["kayip_orani"]=df2["kayip"]/df2["kaynak"]*100

df3["kayitboyut"]=df3["kayitboyut"]-161196
df3["kayip"]=df3["kaynak"]-df3["kayitboyut"]
df3["kayip_orani"]=df3["kayip"]/df3["kaynak"]*100

In [8]:
df1.describe().T

,count,mean,std,min,25%,50%,75%,max
avgRTT,456.0,7.849452e+02,4.979833e+02,1.529720e+02,3.179607e+02,5.836485e+02,1.262539e+03,2.418214e+03
packetLoss,482.0,5.394191e+00,2.261377e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+02
latency,482.0,6.576556e+01,3.624164e+01,0.000000e+00,4.300000e+01,6.150000e+01,8.100000e+01,1.820000e+02
hopCount,482.0,3.074689e+00,1.176088e+00,1.000000e+00,2.000000e+00,3.000000e+00,4.000000e+00,7.000000e+00
bandwidth,482.0,1.000000e+07,0.000000e+00,1.000000e+07,1.000000e+07,1.000000e+07,1.000000e+07,1.000000e+07
psnr,482.0,1.524811e+01,3.615016e+00,8.154574e+00,1.369825e+01,1.412297e+01,1.515473e+01,3.104612e+01
ssim_first,482.0,6.489304e-01,1.184548e-01,4.228950e-01,5.838817e-01,6.092190e-01,6.867715e-01,9.831390e-01
ssim_second,482.0,5.067460e+00,2.690546e+00,2.387453e+00,3.807834e+00,4.080666e+00,5.041386e+00,1.773123e+01
kaynak,482.0,6.720981e+07,0.000000e+00,6.720981e+07,6.720981e+07,6.720981e+07,6.720981e+07,6.720981e+07
kayitboyut,482.0,3.782920e+07,1.588972e+07,1.425672e+07,2.526677e+07,3.313109e+07,4.807330e+07,1.187232e+08
kayip,482.0,2.938061e+07,1.588972e+07,-5.151342e+07,1.913651e+07,3.407872e+07,4.194304e+07,5.295309e+07
kayip_orani,482.0,4.371477e+01,2.364197e+01,-7.664569e+01,2.847280e+01,5.070498e+01,6.240613e+01,7.878773e+01
type,482.0,1.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
real_mos,482.0,2.076763e+00,5.039547e-01,1.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,4.000000e+00

In [9]:
df2.describe().T

,count,mean,std,min,25%,50%,75%,max
avgRTT,465.0,6.513941e+02,6.628845e+02,1.520810e+02,3.032970e+02,4.199690e+02,8.670670e+02,9.611700e+03
packetLoss,482.0,5.117566e+00,2.085018e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+02
latency,482.0,6.911618e+01,8.344933e+01,0.000000e+00,3.800000e+01,5.650000e+01,7.600000e+01,6.690000e+02
hopCount,482.0,3.236515e+00,1.254545e+00,1.000000e+00,2.000000e+00,3.000000e+00,4.000000e+00,7.000000e+00
bandwidth,482.0,1.000000e+07,0.000000e+00,1.000000e+07,1.000000e+07,1.000000e+07,1.000000e+07,1.000000e+07
psnr,482.0,2.148913e+01,5.417610e+00,9.064855e+00,1.831001e+01,1.996861e+01,2.388812e+01,3.647182e+01
ssim_first,482.0,8.824262e-01,1.030775e-01,4.376520e-01,8.577650e-01,8.935485e-01,9.450757e-01,9.959600e-01
ssim_second,482.0,1.097218e+01,4.357062e+00,2.499945e+00,8.469928e+00,9.728481e+00,1.260234e+01,2.393568e+01
kaynak,482.0,6.720981e+07,0.000000e+00,6.720981e+07,6.720981e+07,6.720981e+07,6.720981e+07,6.720981e+07
kayitboyut,482.0,5.824698e+07,6.728800e+06,2.815036e+07,5.357832e+07,5.724834e+07,6.478498e+07,6.720981e+07
kayip,482.0,8.962836e+06,6.728800e+06,0.000000e+00,2.424832e+06,9.961472e+06,1.363149e+07,3.905946e+07
kayip_orani,482.0,1.333561e+01,1.001163e+01,0.000000e+00,3.607854e+00,1.482145e+01,2.028199e+01,5.811570e+01
type,482.0,2.000000e+00,0.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00
real_mos,482.0,2.865145e+00,9.501444e-01,1.000000e+00,2.000000e+00,3.000000e+00,3.000000e+00,5.000000e+00

In [10]:
df3.describe().T

,count,mean,std,min,25%,50%,75%,max
avgRTT,501.0,7.719392e+02,4.383821e+02,1.530840e+02,3.190030e+02,7.282400e+02,1.217746e+03,1.685973e+03
packetLoss,501.0,1.330672e-01,2.218227e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,4.444444e+01
latency,501.0,7.042715e+01,2.507790e+01,1.400000e+01,5.100000e+01,7.000000e+01,8.300000e+01,1.510000e+02
hopCount,501.0,2.660679e+00,7.903358e-01,1.000000e+00,2.000000e+00,3.000000e+00,3.000000e+00,5.000000e+00
bandwidth,501.0,1.000000e+07,0.000000e+00,1.000000e+07,1.000000e+07,1.000000e+07,1.000000e+07,1.000000e+07
psnr,501.0,2.298717e+01,6.185472e+00,1.484019e+01,1.769052e+01,2.112114e+01,2.642454e+01,3.796985e+01
ssim_first,501.0,8.939961e-01,8.572931e-02,6.671770e-01,8.269590e-01,9.128220e-01,9.706310e-01,9.974720e-01
ssim_second,501.0,1.202214e+01,5.252635e+00,4.777868e+00,7.618510e+00,1.059595e+01,1.532108e+01,2.597268e+01
kaynak,501.0,6.720981e+07,0.000000e+00,6.720981e+07,6.720981e+07,6.720981e+07,6.720981e+07,6.720981e+07
kayitboyut,501.0,5.751990e+07,8.710342e+06,3.155823e+07,5.121903e+07,5.908335e+07,6.589909e+07,6.720981e+07
kayip,501.0,9.689910e+06,8.710342e+06,0.000000e+00,1.310720e+06,8.126464e+06,1.599078e+07,3.565158e+07
kayip_orani,501.0,1.441740e+01,1.295993e+01,0.000000e+00,1.950191e+00,1.209119e+01,2.379234e+01,5.304521e+01
h10gelen,501.0,3.827496e+07,3.625271e+07,9.446000e+03,4.960500e+06,2.940698e+07,6.299305e+07,1.440623e+08
h10giden,501.0,2.480220e+07,6.242623e+07,5.379200e+04,5.116170e+05,1.381395e+06,6.446424e+06,4.071262e+08
h10toplam,501.0,2.681572e+08,4.124880e+08,6.367000e+04,1.281506e+07,9.975116e+07,3.544281e+08,2.950395e+09
h14gelen,501.0,5.039130e+07,4.847813e+07,9.326000e+03,1.010838e+07,3.290779e+07,8.442204e+07,1.943895e+08
h14giden,501.0,2.516187e+07,6.310808e+07,5.284400e+04,5.317990e+05,1.434375e+06,6.698421e+06,4.102791e+08
h14toplam,501.0,3.168000e+08,4.482440e+08,6.274400e+04,2.239521e+07,1.304119e+08,4.587961e+08,2.875070e+09
type,501.0,6.000000e+00,0.000000e+00,6.000000e+00,6.000000e+00,6.000000e+00,6.000000e+00,6.000000e+00
real_mos,501.0,3.071856e+00,1.053957e+00,2.000000e+00,2.000000e+00,3.000000e+00,4.000000e+00,5.000000e+00

In [12]:
df1h6=df1[df1["host"]=="h6"]
df2h6=df2[df2["host"]=="h6"]
df3h6=df3[df3["host"]=="h6"]

In [28]:
print(f'Df1 Ortalama ssim_first: {df1["ssim_first"].mean()}, Df1 h6 Ortalma ssim_first: {df1h6["ssim_first"].mean()}')
print(f'Df2 Ortalama ssim_first: {df2["ssim_first"].mean()}, Df1 h6 Ortalma ssim_first: {df2h6["ssim_first"].mean()}')
print(f'Df3 Ortalama ssim_first: {df3["ssim_first"].mean()}, Df1 h6 Ortalma ssim_first: {df3h6["ssim_first"].mean()}')

Df1 Ortalama ssim_first: 0.648930387966805, Df1 h6 Ortalma ssim_first: 0.5799385666666667
Df2 Ortalama ssim_first: 0.8824261825726142, Df1 h6 Ortalma ssim_first: 0.8465811333333334
Df3 Ortalama ssim_first: 0.8939960618762476, Df1 h6 Ortalma ssim_first: 0.8238714516129032

In [23]:
print(f'Df1 Ortalama real_mos: {df1["real_mos"].mean()}, Df1 h6 Ortalma real_mos: {df1h6["real_mos"].mean()}')
print(f'Df2 Ortalama real_mos: {df2["real_mos"].mean()}, Df1 h6 Ortalma real_mos: {df2h6["real_mos"].mean()}')
print(f'Df3 Ortalama real_mos: {df3["real_mos"].mean()}, Df1 h6 Ortalma real_mos: {df3h6["real_mos"].mean()}')

Df1 Ortalama real_mos: 2.0767634854771786, Df1 h6 Ortalma real_mos: 1.9666666666666666
Df2 Ortalama real_mos: 2.8651452282157677, Df1 h6 Ortalma real_mos: 2.066666666666667
Df3 Ortalama real_mos: 3.07185628742515, Df1 h6 Ortalma real_mos: 2.4193548387096775

In [24]:
print(f'Df1 Ortalama latency: {df1["latency"].mean()}, Df1 h6 Ortalma latency: {df1h6["latency"].mean()}')
print(f'Df2 Ortalama latency: {df2["latency"].mean()}, Df1 h6 Ortalma latency: {df2h6["latency"].mean()}')
print(f'Df3 Ortalama latency: {df3["latency"].mean()}, Df1 h6 Ortalma latency: {df3h6["latency"].mean()}')

Df1 Ortalama latency: 65.7655601659751, Df1 h6 Ortalma latency: 47.36666666666667
Df2 Ortalama latency: 69.11618257261411, Df1 h6 Ortalma latency: 64.43333333333334
Df3 Ortalama latency: 70.42714570858283, Df1 h6 Ortalma latency: 47.70967741935484

In [25]:
print(f'Df1 Ortalama hopCount: {df1["hopCount"].mean()}, Df1 h6 Ortalma hopCount: {df1h6["hopCount"].mean()}')
print(f'Df2 Ortalama hopCount: {df2["hopCount"].mean()}, Df1 h6 Ortalma hopCount: {df2h6["hopCount"].mean()}')
print(f'Df3 Ortalama hopCount: {df3["hopCount"].mean()}, Df1 h6 Ortalma hopCount: {df3h6["hopCount"].mean()}')

Df1 Ortalama hopCount: 3.074688796680498, Df1 h6 Ortalma hopCount: 2.2666666666666666
Df2 Ortalama hopCount: 3.236514522821577, Df1 h6 Ortalma hopCount: 2.4
Df3 Ortalama hopCount: 2.6606786427145708, Df1 h6 Ortalma hopCount: 1.6451612903225807

In [26]:
print(f'Df1 Ortalama avgRTT: {df1["avgRTT"].mean()}, Df1 h6 Ortalma avgRTT: {df1h6["avgRTT"].mean()}')
print(f'Df2 Ortalama avgRTT: {df2["avgRTT"].mean()}, Df1 h6 Ortalma avgRTT: {df2h6["avgRTT"].mean()}')
print(f'Df3 Ortalama avgRTT: {df3["avgRTT"].mean()}, Df1 h6 Ortalma avgRTT: {df3h6["avgRTT"].mean()}')

Df1 Ortalama avgRTT: 784.94525, Df1 h6 Ortalma avgRTT: 552.1481034482758
Df2 Ortalama avgRTT: 651.3941483870967, Df1 h6 Ortalma avgRTT: 520.1029666666666
Df3 Ortalama avgRTT: 771.9392035928144, Df1 h6 Ortalma avgRTT: 863.5672903225808

In [27]:
print(f'Df1 Ortalama kayip_orani: {df1["kayip_orani"].mean()}, Df1 h6 Ortalma kayip_orani: {df1h6["kayip_orani"].mean()}')
print(f'Df2 Ortalama kayip_orani: {df2["kayip_orani"].mean()}, Df1 h6 Ortalma kayip_orani: {df2h6["kayip_orani"].mean()}')
print(f'Df3 Ortalama kayip_orani: {df3["kayip_orani"].mean()}, Df1 h6 Ortalma kayip_orani: {df3h6["kayip_orani"].mean()}')

Df1 Ortalama kayip_orani: 43.71476572337558, Df1 h6 Ortalma kayip_orani: 69.04977822781788
Df2 Ortalama kayip_orani: 13.335606759865875, Df1 h6 Ortalma kayip_orani: 25.09246318578205
Df3 Ortalama kayip_orani: 14.417403299230493, Df1 h6 Ortalma kayip_orani: 29.617746116996976